### ISSUE TITLE
Build up a Wiki

### ISSUE THREAD

**Issue by nezort11** [Delta-Konnect/wiki#1]
I am thinking about some kind of _small_ private/internal wiki/**knowledge base**. This might help to _get more information about the field_ to better understand the tasks and have a full picture. It will be very useful both for me and maybe other newcomers to better grasp the sense of this technology.

Resources on the internet might be very different, long and hard to understand. Wiki might include actual, useful, direct information (or links to respected articles), like this (from email):

> RFID can be seen as a modern barcode alternative. Because it's not based on optics but microwaves, you don't need direct line of sight. Reads are recognized up to 6 meters and 200 reads/second are possible. The technology (RFID @UHF band 920MHz) was introduced around 2005, but only now the tag costs fell under a critical price of $0.10 per tag. That's enough to make it interesting for thousands of companies that found it too expensive before.

**Solutions**.

I think enterprise solutions like Notion, Confluence, Sharepoint, Obsidian are too heavy and expensive. GitHub Wikis is a nice, tiny solution but requires paid team license (\$5/user/mo.) to work in private repositories.

So I think we can just write everything inside root `README.md` in separate repo (`delta-konnect/knowledge-base`).

`README.md` can be easly turned into web page (using GitHub Pages's Jukell), but it sadly requires subscription to work with private repos. (maybe it can be public repo?)

What do you think? @techcreation1

**Comment by nezort11** [comment]
I've changed repo visibility to public in order to enable free wiki (you can make it private at any time if you change your mind).

- https://github.com/Delta-Konnect/wiki/wiki

You can read this guide to get started with creating wiki pages (instead of writing everything in a single README.md): https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages

**Comment by techcreation1** [comment]
Need alternatives for Github Wiki that features the following:
- Different access levels based on user permission (e.g. public, private group 1, private group 2, private group 3, admins)
- Clean & modern interface
- Easy to edit
- Self hosted or Cloud serviced
- Free or Cheap (<$20 per month all user included)

Best Feature Rich Alternatives:
https://www.getoutline.com
https://docs.requarks.io/install
https://www.nuclino.com/pricing

**Comment by techcreation1** [comment]
I've started a subscription with _getoutline_

This will be closed for now.
